"""transaction_item model changes

Revision ID: 21f90c865a2a
Revises: 62d21b90f4e9
Create Date: 2025-03-14 07:36:06.566303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21f90c865a2a'
down_revision: Union[str, None] = '62d21b90f4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='customers')
    op.drop_index('phone', table_name='customers')
    op.alter_column('suppliers', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.create_unique_constraint(None, 'suppliers', ['phone'])
    op.add_column('transaction_items', sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_items', 'total')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.alter_column('suppliers', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.create_index('phone', 'customers', ['phone'], unique=True)
    op.create_index('email', 'customers', ['email'], unique=True)
    # ### end Alembic commands ###
